name: Build JavaSwitch NRO

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Java JDK
        run: |
          apt-get update
          apt-get install -y openjdk-17-jdk

      - name: Install dependencies
        run: |
          # On force la mise à jour malgré les erreurs 403 temporaires
          dkp-pacman -Syy --noconfirm || true
      - name: Build NRO
        run: |
          # 1. On définit les chemins
          export PORTLIBS=$DEVKITPRO/portlibs/switch
          export PATH=$PATH:$DEVKITPRO/devkitA64/bin
          
          # 2. On définit les flags de compilation ET de linking
          # Le "-mtls-dialect=desc" règle l'erreur __tls_align
          export CFLAGS="-I$DEVKITPRO/libnx/include -I$PORTLIBS/include -I/usr/lib/jvm/java-17-openjdk-amd64/include -I/usr/lib/jvm/java-17-openjdk-amd64/include/linux"
          export CXXFLAGS="$CFLAGS -mtls-dialect=desc"
          export LDFLAGS="-L$DEVKITPRO/libnx/lib -L$PORTLIBS/lib -mtls-dialect=desc"
          
          make

      - name: Upload NRO
        uses: actions/upload-artifact@v4
        with:
          name: JavaSwitch-NRO
          path: ./*.nro
