name: Build Switch NRO

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare Environment
        run: |
          # On installe seulement Java via les dépôts système (plus fiable)
          apt-get update && apt-get install -y openjdk-17-jdk
          echo "Vérification des fichiers locaux..."
          ls -l deps/specs/switch.specs
          ls -l deps/lib/libnx.a

      - name: Compile Project
        run: |
          # On définit le chemin Java pour les headers JNI
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          # On lance make directement sans 'clean' pour éviter l'erreur No Rule
          make
        env:
          DEVKITPRO: /opt/devkitpro

      - name: Upload NRO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: JavaSwitch-Executable
          path: "*.nro"
