name: Import Java for Minecraft 1.20.1
on: workflow_dispatch

jobs:
  import-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Java 17 for Deps
        run: |
          # Installation de Java 17 (Architecture ARM64 car la Switch est en ARM64)
          sudo apt-get update
          sudo apt-get install -y openjdk-17-jdk-headless
          
          # Création de la structure dans ton repo
          mkdir -p deps/lib
          mkdir -p deps/include/linux
          
          # Copie des fichiers vitaux pour Minecraft (le moteur Java)
          # On cherche la libjvm.so (le coeur de Minecraft)
          JVM_PATH=$(find /usr/lib/jvm/java-17-openjdk-amd64 -name "libjvm.so")
          cp $JVM_PATH deps/lib/
          
          # Copie des Headers (les plans de construction)
          cp /usr/lib/jvm/java-17-openjdk-amd64/include/jni.h deps/include/
          cp /usr/lib/jvm/java-17-openjdk-amd64/include/linux/jni_md.h deps/include/linux/

      - name: Push to Deps
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add deps/
          git commit -m "IMPORT : Moteur Java 17 pour Minecraft Modern" || echo "Déjà à jour"
          git push
