name: Minecraft Native AOT Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_minecraft:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    
    steps:
      - name: Checkout du Repo
        uses: actions/checkout@v4

      - name: Bot Telechargement du Serveur Officiel
        run: |
          mkdir -p romfs
          curl -L -o romfs/server.jar https://piston-data.mojang.com/v1/objects/84194a2f286ef7c14ed7ce0090dba59902951553/server.jar

      - name: Bot Traduction AOT (Java vers C++)
        run: python3 translator.py

      - name: Configuration de l'environnement Switch
        run: |
          # On met a jour les depots et on installe switch-dev (libnx est inclus dedans)
          dkp-pacman -Syu --noconfirm switch-dev

      - name: Compilation du NRO (Moteur + Launcher)
        run: |
          # Utilisation des outils aarch64 pour la Switch
          /opt/devkitpro/devkitA64/bin/aarch64-none-elf-g++ -O2 -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE \
          -I/opt/devkitpro/libnx/include -c main.cpp -o main.o
          
          /opt/devkitpro/devkitA64/bin/aarch64-none-elf-g++ -O2 -march=armv8-a+crc+crypto -mtune=cortex-a57 -mtp=soft -fPIE \
          -I/opt/devkitpro/libnx/include -c minecraft_server_native.cpp -o engine.o
          
          # Liaison finale via ton Makefile
          make

      - name: Exportation du fichier .nro
        uses: actions/upload-artifact@v4
        with:
          name: Minecraft-Native-Switch
          path: ./*.nro
